Convert from&to native mermaid objects, options and copy/download
nopeslide/drawio_mermaid_plugin pull request #16
Opened 2021-03-20 19:07 UTC by rpeyron

Hello,

I have added some more features:

### Ability to configure default properties settings 

From Extra / Configuration menu set defaultMermaidConfig key with mermaid config structure (see mermaid documentation)
![image](https://user-images.githubusercontent.com/3126751/111882252-f015a100-89b4-11eb-9f4a-57bed4b57c11.png)

In a custom draw.io build you can also set the default configuration in PreConfig.js.

### Convert from & to native mermaid objects 

The mermaid plugin is far easier to use than native support, but one nice thing about the native mermaid objects is that they are correctly displayed on every drawio version, even without the plugin (because it is displayed as SVG images). To get the most of the two, from a contextual menu, a menu will allow converting from or to native mermaid objects if the user needs the shape to be displayed even without the plugin.
![image](https://user-images.githubusercontent.com/3126751/111882492-31f31700-89b6-11eb-9be7-5536ecbe96cc.png)

The full settings will be included in native mermaid objects, so they will be rendered consistently (but some difference may occur because of the different mermaid version).

To avoid problems when changing the shape type I have replaced the "this.state.cell.valueChanged"  in mxShapeMermaid.prototype.updateImage  with corresponding instructions in the parse function. It works well on the tests I made, but I hope it was not useful for use cases that I haven't figured out.

### Download and copy to clipboard

Some links are included in the edit window to be able to download image as SVG or PNG, and copy in clipboard as PNG.
![image](https://user-images.githubusercontent.com/3126751/111882505-43d4ba00-89b6-11eb-902f-f1c22b9ad693.png)

I hope you will find these features useful.

Best regards
Remi

2021-03-21 12:03 UTC, nopeslide commented
Hey, thanks again for the PR.
These look like nice features.
Will take a look in a few hours.
Do you use the draw.io desktop version or the vscode integration?

2021-03-21 16:31 UTC, rpeyron commented
Hello, I use the draw.io desktop version

2021-03-30 10:29 UTC, nopeslide requested changes
Sorry it took longer than anticipated.
Regarding your deep diff/merge code, I would prefer external libs.
At least I propose outsourcing these function since you use them in multiple files.
I also had a problem running this plugin against the latest drawio version,
it completely bricked drawio :D
If we access drawio internals, we should at least do exception handling if drawio moves/renames these internals. 

If you see things differently, please say so.

2021-03-30 10:29 UTC, nopeslide commented on drawio_desktop/src/mermaid-plugin.js
> +  mermaid_settings = mergeDeep(mermaid_settings, window.Editor.config.defaultMermaidConfig);
I had problems here with the latest drawio-desktop version.
```suggestion
  mermaid_settings = mergeDeep(mermaid_settings, mermaid_plugin_defaults);
  try {
    mermaid_settings = mergeDeep(mermaid_settings, window.EditorUi.defaultMermaidConfig);
  } catch (e) {
    if (!e instanceof TypeError) {
      throw e;
    }
  }
  try {
    mermaid_settings = mergeDeep(mermaid_settings, window.Editor.config.defaultMermaidConfig);
  } catch (e) {
    if (!e instanceof TypeError) {
      throw e;
    }
  }
```

2021-03-30 19:36 UTC, rpeyron commented on drawio_desktop/src/shapes/shapeMermaid.js
> +// ---
From what I see in the deep-diff documentation, the result is quite different as the one of this function. But it seems there is another npm package that may work like expected : deep-object-diff (even more used and updated that deep-diff).  I will try this one.

2021-03-30 19:58 UTC, rpeyron commented
Hello,  I totally agree with what you suggested, I will work on that this weekend.
About the use of draw.io internals, in addition to the two vars you already fixed I will add some extra checks that are missing when using mermaidData attribute value. And I will also try to do better testing, because the error you encountered actually occurs also on the drawio-desktop version I am using with empty configuration field :-(

2021-03-31 22:44 UTC, nopeslide commented
I never used the built in mermaid feature (I wrote this plugin before I knew it existed), so I assume my config field was/is also simply empty.
And again, props to you, your patches make this drawio plugin a full fledged mermaid editor :D
I just love it. When I have time I will copy some of these features into my wavedrom plugin.
I only write js out of necessity, so I'm really glad about your contributions :)

2021-03-31 22:46 UTC, nopeslide commented on drawio_desktop/src/shapes/shapeMermaid.js
> +// ---
My bad, to be honest I just named the first package I found since this is such a common problem

2021-04-02 20:08 UTC, rpeyron commented
Hello, I have applied the changes discussed above.

2021-04-02 21:02 UTC, nopeslide approved these changes
nice, lgtm

2021-04-02 21:12 UTC, merged